<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>

    <TargetFramework>net8.0-windows</TargetFramework>

    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>

    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <RootNamespace>MacBookStyleForWindows</RootNamespace>
    <AssemblyName>MacBookStyleForWindows</AssemblyName>

    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>

    <Platforms>x64</Platforms>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>

    <PublishReadyToRun>true</PublishReadyToRun>
    <TieredPGO>true</TieredPGO>
    <InvariantGlobalization>true</InvariantGlobalization>

    <Version>1.0.0</Version>
    <Company>MacBookStyleForWindows</Company>
    <Product>MacBook Style for Windows</Product>
  </PropertyGroup>

</Project>
